### ISSUE TITLE
Airtable

### ISSUE THREAD

**Issue by ahoffix** [dlt-hub/verified-sources#129]
# Quick pipeline info
- Name of the pipeline: Airtable
- What is the data source: https://airtable.com/appcChDyP0pZeC76v/tbl1sN4CpPv8pBll4/viwah5azeTMQ9xjO0?blocks=hide 
- I tried following destinations with it: duckdb

# Why it got built?
- [x] I run it for fun
- [x] I run it on my local laptop
- [ ] I run it in production

# How much of your involvement can we expect?
We want to optimize the time you spent on this contribution. To successfully merge the PR we may require some fixes in the submitted code:
- [x] I'm ok with implementing the code review fixes

Things below are 100% optional but are helping us to make your pipeline a `verified` one - with tests and running in our CI
- [x] I can share my test data or a test account with `dltHub`
- [x] I'm ok with writing a short doc

# Additional context
Anything we should know about your pipeline
Use case: collect information about workshop attendees and analyze it compared to other events, e.g. 
- how many events did they attend? 
- how often do more experienced people attend the workshop than less experienced people?

**Comment by willi-mueller** [comment]
Hi, is someone working on this? Otherwise, I might be able to give it a try :)

**Comment by rudolfix** [comment]
@willi-mueller that would be amazing! you can take a look at `sql_database` source - I think this one may work in a similar way. If you decide to do it I'll add you as contributor so you can use our CI, we'll also give you our test account
