### ISSUE TITLE
shopify_dlt pipeline: Missing dependency 'ShopifyAPI' in requirements.txt 

### ISSUE THREAD

**Issue by rahuljo** [dlt-hub/verified-sources#157]
**Pipeline name**
shopify_dlt

**Describe the bug**
After I initiate a shopify project using `dlt init shopify_dlt bigquery`, the `requirements.txt` file only contains:  
```
dlt[bigquery]>=0.2.8
```
So, after running `python shopify_dlt_pipeline.py`, I get the error:  
```bash
Traceback (most recent call last):
  File "shopify_dlt_pipeline.py", line 6, in <module>
    from shopify_dlt import shopify_source
  File "C:\Users\rahul\OneDrive\Desktop\Work\shopify_demo\issue\shopify_dlt\__init__.py", line 6, in <module>
    import shopify
ModuleNotFoundError: No module named 'shopify'
```  
I fix this by doing `pip install ShopifyAPI`

**Expected behavior**
Dependency `ShopifyAPI` should be included in the automatically generated `requirements.txt`

**Running environment**
 - OS: Windows
 - `dlt` Version: 0.2.9

**Comment by rudolfix** [comment]
fixed in #222
