### ISSUE TITLE
[improve] handle KeyError for Notion source

### ISSUE THREAD

**Issue by AstrakhantsevaAA** [dlt-hub/verified-sources#241]
Currently, Notion pipeline fetches data from databases. If we wish to fetch data from custom databases, it requires input like:
```
selected_database_ids = [{"id": "dfgs", "use_name": "ddf"}] 
```
However, if we omit the `use_name`, it results in a `KeyError`. 

TODO:
If the `use_name` isn’t supplied, the code will automatically fetch it from Notion. For instance, you can input:
```
selected_database_ids = [{"id": "fllff"}]
 ```
And the system will retrieve the corresponding `use_name` directly from Notion. It’s a minor adjustment, but I believe it eases user experience.( for me it did)
Before this change, only providing a database ID without the `use_name` would lead to an error. This modification should make the process more user-friendly.

**Comment by dat-a-man** [comment]
PR created : https://github.com/dlt-hub/verified-sources/pull/242

**Comment by rudolfix** [comment]
we should convert Notion into a source that is like our sql_database or incoming Mongo/Airtable where you select databases, then tables and configure them for sync...
