### ISSUE TITLE
CI test runs crash on forks because they do not use the github-action secrets provided

### ISSUE THREAD

**Issue by willi-mueller** [dlt-hub/verified-sources#247]
**Source name**

All sources while doing CI runs on forks.

**Make sure that**
* [x] I checked the README in the source folder
* [x] If I have problems with the credentials I checked the [credentials docs](https://dlthub.com/docs/general-usage/credentials) and [troubleshooting](https://dlthub.com/docs/walkthroughs/run-a-pipeline#4-detect-and-handle-problems)

**Describe the bug**
Please describe the bug. If possible provide us:
1. name of the dlt source causing the problem: all
2. name if the dlt resource causing the problem: all
3. which destination you are loading into: all
4. any stack traces and logs you can share: See https://github.com/dlt-hub/verified-sources/actions/runs/5904871862/job/16017862670?pr=246#step:9:13903

I observed two defects:

1. the CI test runs cannot find the secrets I provided
2. when an existing source is changed the CI does not run only the changed source but a multitude of sources – maybe all? When a new source is added, however, it runs only the new source.

**To Reproduce**
1. make any change in an existing connector or add a new connector
3. add the secret for that source to the `DLT_SECRETS_TOML`
4. make a PR in a fork of the verified-sources repository
5. watch it crash 💥 

**Expected behavior**
The CI run should pick up the secrets I provided in the github settings of my fork.

**Stack traces and other evidence**
Please paste any stack traces, logs and screenshots. Mind that the issue is public!

```
    dlt.common.configuration.exceptions.ConfigFieldMissingException: Following fields are missing: ['private_app_password'] in configuration with spec ShopifySourceConfiguration
E           	for field "private_app_password" config providers and keys were tried in following order:
E           		In Environment Variables key SHOPIFY__SOURCES__SHOPIFY_DLT__SHOPIFY__PRIVATE_APP_PASSWORD was not found.
E           		In Environment Variables key SHOPIFY__SOURCES__SHOPIFY_DLT__PRIVATE_APP_PASSWORD was not found.
E           		In Environment Variables key SHOPIFY__SOURCES__PRIVATE_APP_PASSWORD was not found.
E           		In Environment Variables key SHOPIFY__PRIVATE_APP_PASSWORD was not found.
E           		In secrets.toml key shopify.sources.shopify_dlt.shopify.private_app_password was not found.
E           		In secrets.toml key shopify.sources.shopify_dlt.private_app_password was not found.
E           		In secrets.toml key shopify.sources.private_app_password was not found.
E           		In secrets.toml key shopify.private_app_password was not found.
E           		In Environment Variables key SOURCES__SHOPIFY_DLT__SHOPIFY__PRIVATE_APP_PASSWORD was not found.
E           		In Environment Variables key SOURCES__SHOPIFY_DLT__PRIVATE_APP_PASSWORD was not found.
E           		In Environment Variables key SOURCES__PRIVATE_APP_PASSWORD was not found.
E           		In Environment Variables key PRIVATE_APP_PASSWORD was not found.
E           		In secrets.toml key sources.shopify_dlt.shopify.private_app_password was not found.
E           		In secrets.toml key sources.shopify_dlt.private_app_password was not found.
E           		In secrets.toml key sources.private_app_password was not found.
E           		In secrets.toml key private_app_password was not found.
E           Please refer to https://dlthub.com/docs/general-usage/credentials for more information
```
See https://github.com/dlt-hub/verified-sources/actions/runs/5904871862/job/16017862670?pr=246#step:9:13903

On a side note, I am surprised that not only the changed source runs [but also others](https://github.com/dlt-hub/verified-sources/actions/runs/5904871862/job/16017862670?pr=246#step:9:1).

> Run sources_list="chess facebook_ads google_sheets notion shopify_dlt "

**Running environment**
 - OS: [e.g. Linux, MacOs, Windows]
 - `dlt` Version: 0.3.11
 - Virtualization / Runner [e.g. local, VM, Docker, Composer, Kubernetes]
 - Orchestrator / Deployment platform [e.g. Airflow, github actions, Astronomer, Google Composer, Codespaces]

**Additional context**
I've got a private chat with @rudolfix already running.

**Comment by rudolfix** [comment]
@willi-mueller thanks! so it seems the way I try to run our CI for forks is wrong and we need something else. will ping you back with updates
