### ISSUE TITLE
Slack verified source

### ISSUE THREAD

**Issue by adrianbr** [dlt-hub/verified-sources#251]
# Quick source info
- Name of the source: Slack
- What is the data source: We prefer using the REST api to avoid adding more dependencies (as opposed to their python wrapper)

# Current Status
- to be done

# What source does/will do
- We want to get info about the conversations and engagement. To do so, we will read
- conversations in all public channels https://slack.com/api/conversations.list
- Reactions - Maybe Reactions get or reactions list https://api.slack.com/methods/reactions.get
- access logs https://api.slack.com/methods/team.accessLogs

# Test account / test data
- I'd like `dltHub` to create a test account before we start

# Additional context
Anything we should know about your source
- Make sure the endpoints selected work for free slack tier!
- we would like to load incrementally wherever the api allows incremental extraction

**Comment by sehnem** [comment]
Hey @adrianbr there are a few things about the slack integration.

- I was able to implement the conversations.list endpoint, there is just no filter for incrementally getting the data.
- For the reactions.get endpoint there is an issue, probably the list of all messages will have to be implemented. I created the app as a bot, so it need to be added to the channels before getting the messages, probably it should be done as an admin account, right?
- The team.accessLogs has an issue that it is just available for the admin scope, waiting for one account with this permissions.
