### ISSUE TITLE
Applying user endpoint for Slack Source Integration

### ISSUE THREAD

**Issue by dat-a-man** [dlt-hub/verified-sources#267]
Which source is this for
Slack 

Describe the data you'd like, be specific, link the docs
I've been testing the Slack source, and it works quite well. However, I'd like to suggest an improvements that could make it even better:

The current pipeline fetches the user_id, which is helpful. However, for more insightful analytics, it would also be valuable to retrieve user_name and email address. This would aid in a more granular analysis and offer a more comprehensive user-centric view.

Additional context
Enriching the data with additional user endpoints can lead to better insights for end-users.

I hope these suggestions help in further refining the Slack source integration. Thanks for the great work so far!

**Comment by rudolfix** [comment]
done in #269
