### ISSUE TITLE
[kafka] verified source

### ISSUE THREAD

**Issue by rudolfix** [dlt-hub/verified-sources#273]
# Quick source info
Incrementally reads events from a specified kafka topics.

# Current Status
- [x] I plan to write it

# What source does/will do
The source reads events from a specified topics or set of topics and yields them in configurable chunks. It implements incremental loads so events are not duplicated.

Following use cases should be demonstrated:
- reading events from one topic and dispatching them to tables by event type
- reading events from many topics and dispatching them by topic name
- passing KafkaConsumer directly instead of credentials
- how to configure event and channel metadata that will be passed along with the event

Following authorization methods should be implemented:
- PLAIN, SSL, SASL_PLAIN + SSL, directly pass consumer

Optional: reading topic schemas and converting them into pydantic model that we pass as `columns` to resource. Please investigate

# Test account / test data
- [x] I'd like `dltHub` to create a test account before we start

# Additional context
Incremental loading is tricky and must be well tested. Where to start:
1. dont' use autocommit
2. store the offset information in resource state
3. I do not think we need incremental here. depends how offsets are represented
4. **use the state to cut offset on next run before getting messages, not in this run**

**Comment by nicor88** [comment]
Something more to add to this is issue is:
* Being able to use custom decoders after message consumption.
e.g. in the past, I've been working with 3 type of data serialization with Kafka:
* pure JSON
* pure Avro - the schema is attached in the message
* Avro with schema registry - only the reference to the schema registry is attached in the first 5 bytes, then the avro bytes are in the remaining bytes

Said so, the concept of message Decoding is something that must be configurable.
