### ISSUE TITLE
Code cleanup - some unused bits found in github source

### ISSUE THREAD

**Issue by adrianbr** [dlt-hub/verified-sources#294]
A contributor noted that we have some dirty code in the github source. 

We need to remove unused bits from this and any other sources
example:
github/helpers.py:25: unused function 'get_rest_pages' (60% confidence)
github/helpers.py:41: unused function 'get_reactions_data' (60% confidence)
github/helpers.py:163: unused function '_get_commits' (60% confidence)
github/helpers.py:186: unused function '_get_contributor_data' (60% confidence)
github/settings.py:3: unused variable 'START_DATE' (60% confidence)
github/settings.py:7: unused variable 'REPO_EVENTS_PATH' (60% confidence)

**Comment by adrianbr** [comment]
@dat-a-man i suggest you start with Github and get feedback, once you are done with it, take a look if issues occur on other sources and open separate issues for them

**Comment by dat-a-man** [comment]
okay.

**Comment by dat-a-man** [comment]
@adrianbr please check: https://github.com/dlt-hub/verified-sources/pull/295

**Comment by dat-a-man** [comment]
PR 295, with cleaned code merged to master.
