### ISSUE TITLE
[csv + duckdb] reader

### ISSUE THREAD

**Issue by rudolfix** [dlt-hub/verified-sources#299]
# Quick source info
- Name of the source: [e.g. csv_reader]
- What is the data source: a csv files or a folder with csv files residing on any of fsspec filesystems (ie supported by `filesystem` source)

# Current Status
- [x] I plan to write it

# What source does/will do
The source is able to read a location with can be a single file or a folder with many csv files with the same columns. The user should be able to pass a list of such locations to the source and source should create a separate resource for each location that will extract desired csvs from that location. We may also need to provide resource (table names) for each location. Also see `sql_database` on how to modify resources after they are created (with `apply_hints`)

All locations must correspond to the same bucket. See `filesystem` source on how pass bucket and credentials.

We want to use duckdb as the parsing engine. There's a lot to figure out
1. Duckdb can read from fsspec locations now (but no idea how to pass credentials to it) https://duckdb.org/docs/guides/python/filesystems.html
2. Duckdb can read csvs in batches and yield arrow tables with partial data for given csv file. look in Python documentation and you'll find the correct method
3. Provide convenient interface to pass the config arguments from the source to csv reader in duckdb.
4. Allows for incremental loading via `filesystem` - based on last modified timestamp.

Demos:
We'll need to write a few demos:
1. getting csvs from a bucket from several locations, some of them files, some of them folders - using glob to specify
2. getting only the new files - with modification date
3. `apply_hints` on the resource to convert it into a merge resource with primary key

# Test account / test data
Please see the test data for `filesystem`, You will need access to all our supported buckets and filesystems in order to create additional test data (with cvs)
We want to run tests on all buckets - like we do for `filesystem`

# Additional context
You can implement first version as addon to `filesystem` source so you can use `filesystem` directly. There's already a demo of pandas based csv reader. It is a good starting point.

**Comment by IlyaFaer** [comment]
The source is implemented, so the issue seems to be finished.
