### ISSUE TITLE
[Bing Webmaster] verified source

### ISSUE THREAD

**Issue by willi-mueller** [dlt-hub/verified-sources#310]
# Quick source info
- Name of the source: Bing Webmaster
- What is the data source: Provides data about organic traffic coming via Bing search. You get clicks and impressions per date, page, and query. I just finished working on the [GetPageQueryStats](https://learn.microsoft.com/en-us/dotnet/api/microsoft.bing.webmaster.api.interfaces.iwebmasterapi.getquerytrafficstats?view=bing-webmaster-dotnet) endpoint.

# Current Status
- [ ] I plan to write it
- [ ] I've written it and run it for fun
- [ ] I run it on my local laptop
- [x] I run it in production
- I tried the following destinations with it: duckdb, bigquery

# What source does/will do
Please provide descriptions up to 3 most important use cases that users of this source do. Those use cases will be:
- implemented
- reviewed
- demonstrated in the source demo pipeline script
- documented
use case description is not only targeted at the developers but also by people creating test accounts and doing demos.

# Test account / test data
**still thinking about this question**
- [ ] I'd like `dltHub` to create a test account before we start
- [ ] I have test account and can share my test data or a test account with `dltHub` after we merge the source 

# Additional context
Anything we should know about your source

**Comment by sultaniman** [comment]
PR has been merged now. Thank you very much @willi-mueller 🚀 !
