### ISSUE TITLE
Update Shopify API version to 2023-04

### ISSUE THREAD

**Issue by dat-a-man** [dlt-hub/verified-sources#316]
**Source name**
Name of the affected source as displayed by `dlt init` or present in `sources` folder of this repo.
Shopify
**Make sure that**
* [X] I checked the README in the source folder
* [X] If I have problems with the credentials, I checked the [credentials docs](https://dlthub.com/docs/general-usage/credentials) and [troubleshooting](https://dlthub.com/docs/walkthroughs/run-a-pipeline#4-detect-and-handle-problems)

**Describe the bug**
Verified source: Shopify 
Release schedule
Shopify releases a new API version every 3 months at the beginning of the quarter. Version names are date-based to be meaningful and semantically unambiguous (for example, 2023-01). Below is an example release schedule for 2023:

| Stable version  | Release date       | Date stable version is supported until   |
|----------------|-----------------|----------------------------------------|
| 2023-01            | January 1, 2023 | January 1, 2024                                        |
| 2023-04           | April 1, 2023       | April 1, 2024                                              |
| 2023-07           | July 1, 2023        | July 1, 2024                                               |
| 2023-10           | October 1, 2023 | October 1, 2024                                        |

Please describe the bug:

Shopify API version should be updated to `2023-04` to ensure continued compatibility. The `settings.py` file should be updated accordingly. Any deprecated endpoints or altered functionalities need to be addressed.

Please refer to the official Shopify API release notes for more details on the changes involved in this version: [Link to Shopify API release notes](https://shopify.dev/docs/api/release-notes).

**Additional context**
A user got a mail from Shopify stating that :
At least one custom app has had a deprecated API in the last 14 days. Support for these versions will end on January 2, 2024. Update the apps listed to version 2023-04 or later to ensure they continue to function properly.

**Comment by AstrakhantsevaAA** [comment]
Thanks Aman! Already in work :+1: https://github.com/dlt-hub/verified-sources/pull/314

**Comment by dat-a-man** [comment]
Thanks Alena; I'll close this.
