### ISSUE TITLE
Exceeding Maximum Query Length in HubSpot Pipeline

### ISSUE THREAD

**Issue by dat-a-man** [dlt-hub/verified-sources#330]
**Source name**
Name of the affected source as displayed by `dlt init` or present in `sources` folder of this repo.

**Make sure that**
* [X] I checked the README in the source folder
* [X] If I have problems with the credentials I checked the [credentials docs](https://dlthub.com/docs/general-usage/credentials) and [troubleshooting](https://dlthub.com/docs/walkthroughs/run-a-pipeline#4-detect-and-handle-problems)

**Describe the bug**
Please describe the bug. If possible provide us:
1. hubspot()

**To Reproduce**
I'm encountering an issue when running a pipeline for HubSpot data extraction where the query length exceeds the maximum allowed limit of 2000 symbols. This happens even when specifying a small number of properties.

Steps to Reproduce:
1. Define a list of properties for the pipeline, even with a single item:

```python
DEFAULT_PIPELINES_PROPS_Entered_1 = [
    "hs_date_entered_100452487",
]
```
2. Set up and run the pipeline as follows:
```python
def load_pipelines_1_entered() -> None:
    p = dlt.pipeline(
        pipeline_name="hubspot_pipeline_entered",
        dataset_name="hubspot",
        destination='bigquery',
    )
    load_data = hubspot()
    load_data.deals.bind(props=DEFAULT_PIPELINES_PROPS_Entered_1, include_custom_props=True)
    info = p.run(load_data.with_resources("deals"), table_name="pipelines_entered")
    print(info)
```

**Expected behavior**
The pipeline should execute successfully, extracting the specified properties without exceeding the query length limit.

**Stack traces and other evidence**
The pipeline execution fails with an error indicating that the query length is too long, listing properties that were not explicitly specified:

```
<class 'dlt.extract.exceptions.ResourceExtractionError'> In processing pipe deals: extraction of resource deals in generator deals caused an exception: Your request to Hubspot is too long to process. Maximum allowed query length is 2000 symbols, while your list of properties `age_contact_person,amount,amount_in_home_currency,...` is 2111 symbols long. Use the `props` argument of the resource to set the list of properties to extract from the endpoint.
```

**Running environment**
 - OS: MacOs
 - `dlt` Version [0.4.2]
 - Virtualization / Runner [local]

**Additional context**
This issue occurs even with a minimal list of properties specified.
Include any other relevant details that might help in diagnosing and resolving the issue.

**Comment by IlyaFaer** [comment]
@dat-a-man, we split HubSpot properties on HS-driven (those with the `hs_` prefix) and custom properties (those without the `hs_` prefix).

The `include_custom_props` argument, which is `True` by default, says that the resource will ask for all the possible properties of the CRM object, except those starting with `hs_`. Of course, it may include much more than HubSpot API can handle in one request.

It was implemented like this to allow users to read a lot of fields, without mentioning all of them explicitly. However, we do not control the number of properties in the user's cluster, so they still can hit the limit.

Thus, in fact, you're requesting `DEFAULT_PIPELINES_PROPS_Entered_1` + all the custom properties. If you want to read only `DEFAULT_PIPELINES_PROPS_Entered_1`, you need to do this:

```python
load_data.deals.bind(props=DEFAULT_PIPELINES_PROPS_Entered_1, include_custom_props=False)
```

**Comment by dat-a-man** [comment]
Sure @IlyaFaer , I did what you told and for the same :
```
DEFAULT_PIPELINES_PROPS_Entered_1 = [
    "hs_date_entered_100535635",
    ]
```

when I run this
```
def load_pipelines_1_entered() -> None:

    p = dlt.pipeline(
        pipeline_name="hubspot_pipeline_entered",
        dataset_name="hubspot",
        destination='bigquery',
    )
    load_data = hubspot()
    load_data.deals.bind(props=DEFAULT_PIPELINES_PROPS_Entered_1,include_custom_props=False)
    # Run the pipeline with the HubSpot source connector
    info = p.run(load_data.with_resources("deals"), table_name="pipelines_entered_26Jan")
    print(info)
```

I instead of getting only one custom field asked in the list I get 
<img width="587" alt="Screenshot 2024-01-26 at 08 34 44" src="https://github.com/dlt-hub/verified-sources/assets/98139823/b732540d-98e3-4890-b502-872adefdc13a">
<img width="539" alt="Screenshot 2024-01-26 at 08 35 20" src="https://github.com/dlt-hub/verified-sources/assets/98139823/4dc48283-2244-4794-a23d-8201311dbea6">
<img width="606" alt="Screenshot 2024-01-26 at 08 35 38" src="https://github.com/dlt-hub/verified-sources/assets/98139823/d539f76b-4a33-4255-ab3b-c207deefac3b">


### There are total 128 columns when, I asked only one. This is causing confusion I need extract `hs_date***` type columns to be able to work on pipeline stages. It's working fine for this type of request
```
"closedate",
"createdate",
"estimated_go_live",
"deal_owner",
"csm_owner",
"deal_source",
"deal_source_web",
"hr_tool",
"verticals",
"company_type",
"hs_acv",
"hs_arr",
"employees",
"hs_forecast_amount",
"hs_forecast_probability",
"hs_tag_ids",
"internationalization",
"other_benefits",
"payroll_provider",
"product_plan",
"productfeedback",
"use_case",
"amount",
"estimated_monthly_recurring_revenue",
"hs_mrr",
"hubspot_owner_id",
"hs_createdate",
"main_pain",
"hs_tag_ids",
"internationalization",
````
But when the `hs_data_%` column is requested, it behaves unexpectedly.

**Comment by rudolfix** [comment]
@IlyaFaer can you take a look at the report above? maybe @dat-a-man has outdated version?

**Comment by IlyaFaer** [comment]
@rudolfix, yeah, we had a conversation in Slack. Seems to me the issue is solved.

**Comment by dat-a-man** [comment]
@rudolfix @IlyaFaer, Yeah, it's solved. Can you please close the issue?
