### ISSUE TITLE
Missing dependency for google ads verified source

### ISSUE THREAD

**Issue by akelad** [dlt-hub/verified-sources#457]
### dlt version

any

### Source name

Google Ads

### Describe the problem

Right now if you `dlt init` with a google-ads verified source, and you try to run the pipeline you get the following error:
```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[1], line 3
      1 import dlt
      2 from dlt.common.pipeline import LoadInfo
----> 3 from google_ads import google_ads

File ~/Projects/dlt/google_ads/__init__.py:15
     12 import json
     13 from .helpers.data_processing import to_dict
---> 15 from apiclient.discovery import Resource
     17 try:
     18     from google.ads.googleads.client import GoogleAdsClient  # type: ignore

ModuleNotFoundError: No module named 'apiclient'
```

Reported on slack initially: https://dlthub-community.slack.com/archives/C04DQA7JJN6/p1714847133647889

Seems to be a missing dependency of `google-api-python-client`. We should probably add that to the `requirements.txt` of the google-ads verified source.

### Steps to reproduce

Try to do a `dlt init` with google-ads as the verified source.

### How you are using the source?

I'm considering using this source in my work, but bug is preventing this.

### Operating system

macOS

### Runtime environment

Local

### Python version

?

**Comment by rudolfix** [comment]
@IlyaFaer we declare google ads in requirements but maybe something is still missing. please try to verify that
