### ISSUE TITLE
Postgres

### ISSUE THREAD

**Issue by kning** [dlt-hub/verified-sources#480]
### Source name

Postgres

### Describe the source data.

This is the most common production database and often the first data source people want to replicate to their data warehouse.

### What is your plan for this source.

I want to run it in production

### Use case

Replicate production db to data warehouse like Snowflake

### Describe the desired tables.

Custom to each user

### Who else will benefit?

I see Postgres as a destination and am a little surprised it isn't a source as well. Postgres => data warehouse is often the first data pipeline built for a data team.

**Comment by AstrakhantsevaAA** [comment]
Hi @kning you can use [SQL Databases source](https://dlthub.com/docs/dlt-ecosystem/verified-sources/sql_database) for Postgres, let me know if you have any questions!
