### ISSUE TITLE
rest_api: Pluggable Custom Authentication/Authorization

### ISSUE THREAD

**Issue by willi-mueller** [dlt-hub/verified-sources#524]
### Background

Currently in `rest_api` source, we have a predefined set of auth methods (`BearerTokenAuth`, `APIKeyAuth`,  `HttpBasicAuth`). This works well for built-in auth it lacks flexibility for users who wish to introduce custom auth logic.

### Problem

Users must modify the `rest_api.config_setup.AUTH_MAP` to add new paginators.

Also, we have implemented `OAuth2ClientCredentials` and `OAuthJWTAuth` but users cannot configure them with the declarative interface because they are not present in the `AUTH_MAP`.

### Proposal

Introduce a pluggable auth system that allows users to define and register custom auth methods dynamically. This should have a registration function to add new auth methods without adding duplicates.

Also, add the 

#### Example

```python
from dlt.sources.helpers.rest_client.auth import AuthConfigBase

class CustomAuth(AuthConfigBase):
    ...

# Register the custom paginator
register_paginator("custom_auth", CustomAuth)
```

### Tasks

- [x] Update the `rest_api` source to support pluggable auth.
- [x] Add tests.
- [x] Update the docs in the dlt repo.

Follow-up:
- #557

**Comment by burnash** [comment]
Hey @willi-mueller, thanks for the suggestion. I agree let's extend the auth to be pluggable as well.
